### ISSUE TITLE
initial snapshot file

### ISSUE THREAD

**Issue by jaywlm** [stevesloka/envoy-xds-server#1]
can you provide a sample file of snapshot, thanks.

code:
       // Create initial snapshot from file
	proc.ProcessFile(watcher.NotifyMessage{
		Operation: watcher.Create,
		FilePath:  watchDirectoryFileName,
	})

**Comment by jaywlm** [comment]
sample of snapshot file
----------------------------------
```
name: test-cluster
spec:
  listeners:
    - name: test-cluster
      address: 0.0.0.0
      port: 10000
      routes:
        - name: r1
          prefix: /
          clusters: 
            - test-a
  clusters:
    - name: test-a
      endpoints:
        - address: 192.168.50.4
          port: 85
        - address: 192.168.50.4
          port: 86
```
